version: '3'
services:
  nginx:
    build:
      context: .
      target: prod
    ports: 
      - 25565:25565
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "5"