version: '3'
services:
  nginx:
    build: .
    ports: 
      - 25565:25565
    logging:
      driver: "json-file"
      options:
        labels: "servicename"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        max-size: "100m"
        max-file: "5"